# -*- coding: utf-8 -*-
data = {'stop_remote_server': {'args': [],
                               'doc': 'Stops the remote server.\n\nThe server may be configured so that users cannot stop it.'},
        'moveMouseToDisplay': {'args': ['display', 'x', 'y'], 'doc': 'Move Mouse To Display\n'},
        'setDisplay': {'args': ['arg0'], 'doc': 'Set Display\nSets the display to look at.\n'},
        'moveMouseTo': {'args': ['x', 'y'], 'doc': 'Move Mouse To\n'}, 'ping': {'args': [], 'doc': 'Ping\n'},
        'setResultPath': {'args': ['arg0'],
                          'doc': 'Set Result Path\nThe result path should be defined as a relative path\nbased on where log files are written to.\n'},
        'setPsm': {'args': ['psm'],
                   'doc': 'Set PSM\nExisting Modes\n0  OSD_ONLY Orientation and script detection (OSD) only.\n1  AUTO_OSD Automatic page segmentation with OSD.\n2  AUTO_ONLY Automatic page segmentation, but no OSD, or OCR.\n3  AUTO Fully automatic page segmentation, but no OSD. (Default)\n4  SINGLE_COLUMN Assume a single column of text of variable sizes.\n5  SINGLE_BLOCK_VERT_TEXT Assume a single uniform block of vertically aligned text.\n6  SINGLE_COLUMN Assume a single uniform block of text.\n7  SINGLE_LINE Treat the image as a single text line.\n8  SINGLE_WORD Treat the image as a single word.\n9  CIRCLE_WORD Treat the image as a single word in a circle.\n10 SINGLE_CHAR Treat the image as a single character.\n11 SPARSE_TEXT Sparse text. Find as much text as possible in no particular order.\n12 SPARSE_TEXT_OSD Sparse text with OSD.\n13 RAW_LINE Raw line. Treat the image as a single text line, bypassing hacks that are Tesseract-\n'},
        'releaseKey': {'args': ['key'],
                       'doc': 'Releases the requested key\n\nAvailable Options:\n - ENTER\n - BACK_SPACE\n - TAB\n - CANCEL\n - CLEAR\n - SHIFT\n - CONTROL\n - ALT\n - PAUSE\n - CAPSLOCK\n - ESCAPE\n - SPACE\n - PAGE_UP\n - PAGE_DOWN\n - END\n - HOME\n - LEFT\n - UP\n - RIGHT\n - DOWN\n - DELETE\n - F1\n - F2\n - F3\n - F4\n - F5\n - F6\n - F7\n - F8\n - F9\n - F10\n - F11\n - F12\n - F13\n - F14\n - F15\n - F16\n - F17\n - F18\n - F19\n - F20\n - F21\n - F22\n - F23\n - F24\n - PRINT_SCREEN\n - INSERT\n - HELP\n - META\n - A\n - B\n - C\n - D\n - E\n - F\n - G\n - H\n - I\n - J\n - K\n - L\n - M\n - N\n - O\n - P\n - Q\n - R\n - S\n - T\n - U\n - V\n - W\n - X\n - Y\n - Z\n'},
        'findImage': {'args': ['image'], 'doc': 'Find Image\n'},
        'setPollRate': {'args': ['Set Poll Rate'], 'doc': 'Set Poll Rate\n'},
        'getImagePaths': {'args': [], 'doc': 'Get Image Paths\n'},
        'type': {'args': ['message'], 'doc': 'Types the given message\n'},
        'setCaptureRegion': {'args': ['arg0', 'arg1', 'arg2', 'arg3'],
                             'doc': 'Set Capture Region\nSets the display to look at.\n'},
        'click': {'args': ['button', 'count=1'],
                  'doc': 'Simulates a Mouse click\nAvailable options are:\n - LEFT\n - MIDDLE\n - RIGHT\n'},
        'addImagePath': {'args': ['path'], 'doc': 'Add Image Path\n'}, 'holdKey': {'args': ['key'],
                                                                                   'doc': 'Holds the requested key. It wont be released until the release key has been called\n\nAvailable Options:\n - ENTER\n - BACK_SPACE\n - TAB\n - CANCEL\n - CLEAR\n - SHIFT\n - CONTROL\n - ALT\n - PAUSE\n - CAPSLOCK\n - ESCAPE\n - SPACE\n - PAGE_UP\n - PAGE_DOWN\n - END\n - HOME\n - LEFT\n - UP\n - RIGHT\n - DOWN\n - DELETE\n - F1\n - F2\n - F3\n - F4\n - F5\n - F6\n - F7\n - F8\n - F9\n - F10\n - F11\n - F12\n - F13\n - F14\n - F15\n - F16\n - F17\n - F18\n - F19\n - F20\n - F21\n - F22\n - F23\n - F24\n - PRINT_SCREEN\n - INSERT\n - HELP\n - META\n - A\n - B\n - C\n - D\n - E\n - F\n - G\n - H\n - I\n - J\n - K\n - L\n - M\n - N\n - O\n - P\n - Q\n - R\n - S\n - T\n - U\n - V\n - W\n - X\n - Y\n - Z\n'},
        'pressKeys': {'args': ['keys'],
                      'doc': 'presses a set of keys, then releases them immediately afterwords.\n\nAvailable Options:\n - ENTER\n - BACK_SPACE\n - TAB\n - CANCEL\n - CLEAR\n - SHIFT\n - CONTROL\n - ALT\n - PAUSE\n - CAPSLOCK\n - ESCAPE\n - SPACE\n - PAGE_UP\n - PAGE_DOWN\n - END\n - HOME\n - LEFT\n - UP\n - RIGHT\n - DOWN\n - DELETE\n - F1\n - F2\n - F3\n - F4\n - F5\n - F6\n - F7\n - F8\n - F9\n - F10\n - F11\n - F12\n - F13\n - F14\n - F15\n - F16\n - F17\n - F18\n - F19\n - F20\n - F21\n - F22\n - F23\n - F24\n - PRINT_SCREEN\n - INSERT\n - HELP\n - META\n - A\n - B\n - C\n - D\n - E\n - F\n - G\n - H\n - I\n - J\n - K\n - L\n - M\n - N\n - O\n - P\n - Q\n - R\n - S\n - T\n - U\n - V\n - W\n - X\n - Y\n - Z\n'},
        'setTimeoutTime': {'args': ['timeoutTime'], 'doc': 'Set Timeout Time\n'},
        'moveMouseToImage': {'args': ['image'],
                             'doc': 'Move Mouse To Image\nMoves the mouse to the center of the matched image on the screen.\n'},
        'setMouseMoveSpeed': {'args': ['speed'], 'doc': 'Set Mouse Move Speed'},
        'setMinSimilarity': {'args': ['Minimum Similarity'], 'doc': 'Set Min Similarity\n'},
        'moveMouse': {'args': ['xRelative', 'yRelative'],
                      'doc': 'Move Mouse\nMoves the mouse a relative distance based on its original location.\n'},
        'shutdown': {'args': [], 'doc': 'Shutdown\nShuts down JSnagTest\n'},
        'start': {'args': ['port'], 'doc': 'Starts the Snag Test Service'},
        'connect': {'args': ['port'], 'doc': 'Connects to the Snag Test Service'}}
